### ISSUE TITLE
Can't undo decode/encode

### ISSUE THREAD

**Issue by chess-levin** [m4ns0ur/Base64-Helper-IntelliJ-Plugin#1]
Great Tool.

I would appreciate if it's possible to undo any conversion with your tool with ctrl+z.

Now I get an error popup when using undone after a conversion.

I'm using: Intellij 2019.1.2 Ultimate

**Comment by m4ns0ur** [comment]
Fixed in https://github.com/m4ns0ur/Base64-Helper-IntelliJ-Plugin/commit/0f30ebe9daa2d55eb9420aaee800da143f2fa2b1
